### ISSUE TITLE
Diff ➕ & ➖  for Added & Deleted lines *[CSS Provided]*

### ISSUE THREAD

**Issue by nitin2953** [pomber/git-history#184]
https://gist.github.com/nitin2953/e3c7a8bc4a4805c97963671f2b3790da

```css
code div[style*="opacity: 1;"] {
    overflow: visible !important;
}

code div[style*="opacity: 1;"]::before {
    content: "+";
    position: absolute;
    left: -30px;
    color: #00ff4a;
    font-weight: 600;
    scale: 1.3;
}

code div[style*="transform: translateX(-250px);"] {
    transform: none !important;
    opacity: 1 !important;
    overflow: visible !important;
    clip-path: inset(-5px 100% -5px -35px);
    position: relative;
}

code div[style*="transform: translateX(-250px);"]::before {
    content: "_";
    position: absolute;
    top: -16px;
    left: -29.5px;
    color: red;
    font-weight: 600;
    scale: 1.5;
}
```

👆 to quickly find Added/Removed lines, when scrolling fast through long file
Maintainers could (modify &) add it in site css or link to it in Readme.md, for users using extension like Stylus
